print("Hi, nice to meet you!")
print()
myName = input("What's your name? ")
myFood = input("What's your favorite food? ")
myMusic = input("What's your favorite music? ")
myHome = input("Where do you live? ")
print()
print()
print("Hi")
print(myName)
print("You're probably in the mood for")
print(myFood)
print("and want eat it while listening to")
print(myMusic)
print("living in beautiful")
print(myHome)
print("Have a fantastic day!")